Repository wecode-bootcamp-korea/33-1st-CatCoDog-frontend, pull requests merged in 2022-06, with the labels that each got.

#14 [33기 윤경연] Footer Css수정 Feature/footer
  src/components/footer/Footer.scss
  src/pages/Main/Main.js
  src/slideBanner.json
Labels: 완료

#4 [33기 김철회] ADD : 상품 리스트 내의 카테고리 페이지 내 이동 구현
  public/data/data.json
  src/Router.js
  src/components/nav/Nav.scss
  src/pages/Detail/Detail.js
  src/pages/List/List.js
  src/pages/List/Product.scss
  src/pages/List/ProductList.scss
  src/pages/List/ProductListNav.js
  src/pages/List/ProductListNav.scss
  src/pages/List/ProductListPage.js
  src/pages/List/filterData.js
  src/pages/List/navNameData.js
  src/pages/Main/Main.js
  src/pages/list/ ProductList.js
  src/pages/list/List.scss
  src/pages/list/Product.js
Labels: 멘토 리뷰 요청

#11 [33기 남하임] 마이페이지 레이아웃 구성 중 Feature/mypage
  src/pages/Main/Main.js
  src/pages/login/MyPage.js
  src/pages/login/MyPage.scss
  src/pages/login/component/BenefitDetails.js
  src/pages/login/component/BenefitDetails.scss
  src/pages/login/component/ListName.js
  src/pages/login/component/ListName.scss
  src/pages/login/component/TableList.js
  src/pages/login/component/TableList.scss
Labels: 멘토 리뷰 요청

#15 [33기 윤경연] main 오타수정 Feature/feed_layout
  public/images/set8.png
  src/Router.js
  src/components/NavBottom/NavBottom.scss
  src/components/RollingBanner/RollingBanner.js
  src/components/RollingBanner/RollingBanner.scss
  src/components/RollingBannerWindow/RollingBannerWindow.js
  src/components/RollingBannerWindow/RollingBannerWindow.scss
  src/components/nav/Nav.js
  src/pages/Main/Main.js
  src/pages/Main/MainRouter.js
  src/slideBanner.json
Labels: 멘토 리뷰 요청

#13 [33기 윤경연] Nav map 추가 Feature/nav
  src/Router.js
  src/components/NavBottom/NavBottom.js
  src/components/nav/Nav.js
  src/components/nav/Nav.scss
  src/pages/login/SignUp.js
Labels: 멘토 리뷰 요청

#5 [33기 안성주] ADD : 제품 상세 페이지 리펙토링 & 기능 구현 중
  public/data/commentdata.json
  public/data/goodsdata.json
  public/images/smallGoods1.png
  public/images/smallGoods2.png
  public/images/smallGoods3.png
  public/images/smallGoods4.png
  public/images/smallGoods5.png
  public/index.html
  src/pages/Detail/Detail.js
  src/pages/Detail/DetailGoods/DetailGoods.js
  src/pages/Detail/DetailGoods/DetailGoods.scss
  src/pages/Detail/DetailGoodsNav/DetailGoodsNav.js
  src/pages/Detail/DetailGoodsNav/DetailGoodsNav.scss
  src/pages/Detail/ReviewComment/Comment/Comment.js
  src/pages/Detail/ReviewComment/Comment/Comment.scss
  src/pages/Detail/ReviewComment/ReviewComment.js
  src/pages/Detail/ReviewComment/ReviewComment.scss
  src/pages/Detail/ReviewSummary/ReviewSummary.js
  src/pages/Detail/ReviewSummary/ReviewSummary.scss
  src/pages/Detail/Star/Star.js
  src/pages/Detail/Star/Star.scss
  src/pages/Main/MainRouter.js
  src/pages/detail/Detail.scss
  src/styles/variables.scss
Labels: 수정 요청
